version: "3.3"
services:
  mongo:
    image: mongo:7.0.7
    container_name: pdmongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
  nest:
    depends_on:
      - mongo
    image: node:20
    restart: "always"
    volumes:
      - ./:/nest-app/
    ports:
      - 8000:8000
    working_dir: /nest-app/
    entrypoint: npm run start:dev
    links:
      - "mongo:mongo"